# - Data Summarization of Palmer Penguins Data -

#install packages
install.packages("tidyverse")
library(tidyverse)

#install remotes
install.packages("remotes")
#install data
remotes::install_github("allisonhorst/palmerpenguins")
library(palmerpenguins)
penguins

#check if data imported
library(palmerpenguins)
penguins

#looking at data using glimpse
glimpse(penguins)

# $ is way of telling R that something is a variable

#exploring data
unique(penguins$species)
unique(penguins$island)

#binary variable is one with two options: yes/no, true/false

#continuous variable cannot expect to answer binary questions (ex: age, bmi, etc.)

#continuation of previous weeks code

#variable class
class(penguins$sex)
class(penguins$body_mass_g)

#if class is "factor" then variable is binary. if class is "integer" then variable is continuous

#variable levels
levels(penguins$sex)


#Assignment 3; Prompt 1 

class(penguins$species)
class(penguins$island)
class(penguins$bill_length_mm)
class(penguins$bill_depth_mm)
class(penguins$flipper_length_mm)
class(penguins$body_mass_g)
class(penguins$sex)

levels(penguins$species)
levels(penguins$island)
levels(penguins$bill_length_mm)
levels(penguins$bill_depth_mm)
levels(penguins$flipper_length_mm)
levels(penguins$body_mass_g)
levels(penguins$sex)


#Missing Data
is.na(penguins)

#analysis with NA value
penguins %>%
  group_by(island) %>%
  summarise(mean(bill_length_mm))
  
#identify missing data

penguins %>%
  #group_by(species) %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.)))) %>%
  pivot_longer(cols = 1:7, names_to = 'columns', values_to = 'NA_count') %>%
  arrange(desc(NA_count)) %>%
  ggplot(aes(y = columns, x = NA_count)) + geom_col(fill = '#F0E442') + geom_label(aes(label = NA_count)) + 
  # scale_fill_manual(values = c("darkorange", "purple", "cyan4")) + theme_minimal() + 
  labs(title = 'Palmer Penguins NA Count')

#data summarization: bar graph

penguins %>%
  drop_na() %>%
  count(sex, species) %>%
  ggplot() + geom_col(aes(x = species, y = n, fill = species)) + geom_label(aes(x = species, y = n, label = n)) + 
  scale_fill_manual(values = c("#009E73", "#CC79A7", "gray")) +
  facet_wrap(~sex) +
  theme_minimal() +
  labs(title = 'Penguins Species by Gender')
  
#above code gives "error: unexpected symbol in: "theme_minimal () + labs(title = 'Penguins "


#Assignment 3; Prompt 2

# Bar graph counts > colorblind palettes
penguins %>%
  count(species) %>%
  ggplot () + geom_col(aes(x = species, y = n, fill = species)) +
  geom_label(aes(x = species, y = n, label = n)) +
  scale_fill_manual(values = c("#009E73", "#CC79A7", "gray")) +
  labs(title = 'Penguins Species Count')
  
#Change title of graph
penguins %>%
  count(species) %>%
  ggplot () + geom_col(aes(x = species, y = n, fill = species)) +
  geom_label(aes(x = species, y = n, label = n)) +
  scale_fill_manual(values = c("#009E73", "#CC79A7", "gray")) +
  labs(title = 'Number of Penguins Per Species')
  
  
#data summarization
summary(penguins)


#Assingment 3; Prompt 3

summary(penguins$bill_depth_mm)
summary(penguins$bill_length_mm)
summary(penguins$flipper_length_mm)



